update
upgrade

tap Homebrew/dupes
tap phinze/homebrew-cask
tap caskroom/versions
install brew-cask

# cask
cask install hall
cask install firefox-aurora
cask install skype
cask install thunderbird
cask install macvim-kaoriya
cask install mysql-workbench
cask install firefox
cask install google-chrome
cask install google-chrome-canary
cask install keyremap4macbook
cask install alfred
cask install freemind
cask install vagrant
cask install virtualbox
cask alfred link

# brew
install ack
install autoconf
install automake
install bison
install boost
install ctags
install curl
install erlang
install flex
install git
install highlight
install libmemcached
install libxml2
install memcached
install mercurial
install mysql
install nkf
install python
install python3
install subversion --unicode-path
install tree
install varnish
install w3m
install wget
install zsh
install httpd
install zsh-completions
install zsh-syntax-highlighting
install rbenv
install ruby-build
install pyenv
